FROM node:20-alpine
WORKDIR /app
COPY client/package.json client/package-lock.json* client/pnpm-lock.yaml* ./client/
RUN cd client && npm install
COPY client ./client
WORKDIR /app/client
EXPOSE 5173
CMD ["npm", "run", "dev", "--", "--host"]
