FROM node:20-alpine
WORKDIR /app
COPY server/package.json server/package-lock.json* ./server/
RUN cd server && npm install
COPY server ./server
WORKDIR /app/server
EXPOSE 8080
CMD ["npm", "run", "dev"]
